server:
  port: 9091

spring:
  application:
    name: admin-server
  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASS:admin}

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

info:
  app:
    name: Admin Server
    version: 2.0.0
