apiVersion: v1
kind: Secret
metadata:
  name: organization-service-secret
  namespace: default
  labels:
    app: organization-service
type: Opaque
stringData:
  DB_USER: "org_user"
  DB_PASS: "org_pass"
