apiVersion: v1
kind: Service
metadata:
  name: organization-service
  namespace: default
  labels:
    app: organization-service
spec:
  type: ClusterIP
  selector:
    app: organization-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
