apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: default
  labels:
    app: api-gateway
type: Opaque
stringData:
  JWT_SECRET: "nordin-secret-key-para-desarrollo-minimo-256-bits"
