apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: default
  labels:
    app: auth-service
data:
  DB_HOST: "auth-db"
  DB_PORT: "5432"
  DB_NAME: "auth_db"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  ZIPKIN_HOST: "zipkin"
