apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dept-db-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dept-db
  namespace: default
  labels:
    app: dept-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dept-db
  template:
    metadata:
      labels:
        app: dept-db
    spec:
      containers:
        - name: dept-db
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "dept_db"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: department-service-secret
                  key: DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: department-service-secret
                  key: DB_PASS
          volumeMounts:
            - name: dept-db-storage
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "dept_user", "-d", "dept_db"]
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
      volumes:
        - name: dept-db-storage
          persistentVolumeClaim:
            claimName: dept-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: dept-db
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dept-db
  ports:
    - port: 5432
      targetPort: 5432
