apiVersion: v1
kind: Service
metadata:
  name: employee-service
  namespace: default
  labels:
    app: employee-service
spec:
  # ClusterIP — solo accesible dentro del cluster
  # CoreDNS resuelve: employee-service → employee-service.default.svc.cluster.local
  type: ClusterIP
  selector:
    app: employee-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
