apiVersion: v1
kind: Secret
metadata:
  name: department-service-secret
  namespace: default
  labels:
    app: department-service
type: Opaque
stringData:
  DB_USER: "dept_user"
  DB_PASS: "dept_pass"
