apiVersion: v1
kind: Service
metadata:
  name: department-service
  namespace: default
  labels:
    app: department-service
spec:
  type: ClusterIP
  selector:
    app: department-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
